allowBuilds:
  esbuild: true
  msw: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@amazecontinuityprojects/amazeui@1.6.1'
onlyBuiltDependencies:
  - esbuild
  - msw
  - unrs-resolver
overrides:
  hono: 4.12.25
